### ISSUE TITLE
Only format files that changed

### ISSUE THREAD

**Issue by yuvalprtn** [axel-op/googlejavaformat-action#1]
Hi @axel-op 
First of all let me congratulate and thank you for a great GitHub action
Wanted to know if you have a setup or an example for running the action whenever a PR is opened or changed, or maybe triggered manually with a special comment on the PR but running on the change-set meaning running on the files changed only.
Running on the whole repository, when this gets big, and having a large group working on this repository will most likely lead to conflicts.

Any thoughts?

**Comment by axel-op** [comment]
Thanks for the suggestion. I do not have implemented this by now. I thought that this action would be triggered once PRs have been merged on the master branch, so it will push an only commit instead of multiple commits each time a new one is added to the PRs.

I'll think about a way to implement this. If you have an idea, don't hesitate to make a pull request :)

**Comment by axel-op** [comment]
On second thought, I think you should be able to implement this behaviour by editing your workflow file directly, if you commit the files you want by yourselves in a step following this action.

Something like this should do the trick:

```yml
name: Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: axel-op/googlejavaformat-action@v2.0.0
        with:
          skipCommit: true
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "Base ref: $GITHUB_BASE_REF"
            FILES_CHANGED=$(git diff --name-only $GITHUB_BASE_REF HEAD)
            echo "Files changed: $FILES_CHANGED"
            git commit -m "Google Java Format" $FILES_CHANGED
          else
            git commit -m "Google Java Format" -a
          fi
          git push
```

I haven't tested it. If you do so, please tell me how it worked!

**Comment by axel-op** [comment]
Here's an even simpler version of this last step:

```yml
      ...
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
            echo "Files changed: $FILES_CHANGED"
            git commit -m "Google Java Format" $FILES_CHANGED
          else
            git commit -m "Google Java Format" -a
          fi
          git push
```

**Comment by yuvalprtn** [comment]
Thanks Axel
If I get your suggestion correctly the action will format the whole repository and later select the PR's modified files and then generate a commit.
What I suggest is to alter the action to accept parameters using
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswith
Or
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswithargs
And then you can use GitHub's event JSON to pass the list of changed files.
The Java formatter you use is accepting list of files so you can pass exactly what you get 
see https://github.com/google/google-java-format#from-the-command-line

Another approach is to use GitHub's javascript's SDK to get the list of changed files from within your `index.js` code

What do you say?

**Comment by axel-op** [comment]
So what you want to do is to hard code the files you want to edit in your yaml file?

And why are you unsatisfied with my suggestion?

**Comment by yuvalprtn** [comment]
Hi @axel-op maybe I was not clear, I did not mean to have the files hardcoded.
I meant that the default behavior is to format all java files as you explain in your 
> A pattern to match the files to format. The default is **/*.java, which means that all Java files in your repository will be formatted.
The `run:` option you suggest is good but it will happen after all files are formatted, which will take time in  large repositories. So if I have 5,000 files and just pushed a PR with 3 file changes I will format 5,000 files to pick the 3 files I changed.

I think there is an option using https://github.com/actions/toolkit/tree/master/packages/core to receive the list of files affected by the PR and then your action will always work on the files changed (or this can be another parameter - `global` or `changed`)

I will try to free some time to look at it myself as well
Again, great action! Thanks

**Comment by axel-op** [comment]
But is it really worth it? How long does it take to format all of your 5000 files? It cannot be that bad

**Comment by yuvalprtn** [comment]
The action is part of a set of additional actions and build validations, so you are right it is not a huge problem but it may add up.
BTW another idea for extending the action is to have it analyze a comment, like this example https://github.com/cirrus-actions/rebase
So you could have the action run when someone is commenting `/google-format`

**Comment by yuvalprtn** [comment]
Going to try this one out

```yaml
name: Google Formatter

on:
  issue_comment:
    types: [created]

jobs:
  formatting:
    name: Formatter
    if: contains(github.event.comment.body, '/google-format')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: axel-op/googlejavaformat-action@v2.0.0
        with:
          skipCommit: true
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          echo "Base ref: $GITHUB_BASE_REF"
          FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
          echo "Files changed: $FILES_CHANGED"
          git commit -m "Google Java Format\n" $FILES_CHANGED
          git push
```
