### ISSUE TITLE
[Bug] Google Java Format fails on Java 16's Pattern Matching

### ISSUE THREAD

**Issue by PCOffline** [axel-op/googlejavaformat-action#17]
**Description of the Bug**
When using [Java 16's `instanceof` syntax](https://todd.ginsberg.com/post/java-16/instanceof), the action fails.

**Code the Action Fails On**
```Java
if (icon instanceof GuiButton button) { // Line 44
  buttons.put(button.itemPosition, button);
}
```

**Error Printed In the Logs**
```
/home/runner/work/FallenPluginTesting/FallenPluginTesting/src/main/java/ch/dlyn/fallenplugin/gui/StaticGui.java:44:37: error: ')' expected
/home/runner/work/FallenPluginTesting/FallenPluginTesting/src/main/java/ch/dlyn/fallenplugin/gui/StaticGui.java:44:38: error: not a statement
/home/runner/work/FallenPluginTesting/FallenPluginTesting/src/main/java/ch/dlyn/fallenplugin/gui/StaticGui.java:44:44: error: ';' expected
Error: Google Java Format failed with exit code 1
```

**Versions**
Google Style Guide: 1.11.0
Google Java Format Action: 3.4.0

**Action YAML File**
```YAML
name: Google Java Format

on: [push, pull_request]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          commitMessage: "refactor: Google Java style guide"
          args: "--replace"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          version: 1.11.0
```

**Comment by axel-op** [comment]
Hello,

I'm pretty sure the default version of the JDK used on GitHub runners is 11, and this must explain why you have this error: you're using Java 11. Try to explicitly set up the JDK version with the `setup-java` action:

```yml
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-java@v2
         with:
           java-version: 16
       - uses: axel-op/googlejavaformat-action@v3.4.0
         with:
           # ...
```
