### ISSUE TITLE
[BUG] instanceof not supported

### ISSUE THREAD

**Issue by Rouliiian** [axel-op/googlejavaformat-action#23]
Hello @axel-op, thanks you for your action, it's very useful. 😉

Today, in my java project, i need to use a "instanceOf" operator. When the action running, i got a error like this:

```
/home/runner/work/.../.../api/src/main/java/com/.../.../.../api/configuration/Slf4jMDCFilter.java:65:98: error: ')' expected
/home/runner/work/.../.../api/src/main/java/com/.../.../.../api/configuration/Slf4jMDCFilter.java:65:99: error: not a statement
/home/runner/work/.../.../api/src/main/java/com/.../.../.../api/configuration/Slf4jMDCFilter.java:65:108: error: ';' expected
```

Source Code :
```
if ( null != auth.getPrincipal() && auth.getPrincipal() instanceof DefaultOAuth2User principal) {
  MDC.put(...);
}
```

I saw the PR on [Google Java Project](https://github.com/google/google-java-format/commit/32b63aa2e4675cb03fb853ea84cbc37792e442a4)

For the moment i using regex [ExcludedFile](https://github.com/marketplace/actions/google-java-format#files-excluded), but i would like up the problem.

I can't share anymore cuz it's a organisation project, so private. 🤐

Goodbye

**Comment by axel-op** [comment]
Hey @Rouliiian, it seems like you're trying to use this action with Java files containing pattern matchings. "Pattern matching" is a feature introduced with Java 16. Have you tried running the action with a version of the JDK >= 16? See [here]( https://github.com/axel-op/googlejavaformat-action/issues/21#issuecomment-1173111566_) for an example.

**Comment by Rouliiian** [comment]
Hi @axel-op
Your example work with me ! Thanks you again :) 
My code for other people
```
formatting:
    name: Keep calm and Formatting 👑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #Setup java 17
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt-openj9
      #https://github.com/axel-op/googlejavaformat-action
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"
          commitMessage: "refactor: auto format code"
```
