### ISSUE TITLE
This action logs the contents of every scanned Java file

### ISSUE THREAD

**Issue by damien-swarm** [axel-op/googlejavaformat-action#25]
I hope I'm just using this plugin wrong, but when I tried using it with `--set-exit-if-changed`:
```yaml
  java_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven
    - name: Check Java formatting
      uses: axel-op/googlejavaformat-action@v3
      with:
        files: |
          **/*.java
          !**/generated/**
        args: "--set-exit-if-changed"
```
it logs the contents of every single scanned Java file to the Github actions logs (tens of thousands of lines). This is not useful and makes it harder to find actual errors. In fact, in my most recent run, I got `Error: Google Java Format failed with exit code 1` without any "Actual vs Expected" errors :(
