### ISSUE TITLE
Cut new version to include update to Node16

### ISSUE THREAD

**Issue by GeofferyMedved** [axel-op/googlejavaformat-action#27]
I see you've [merged](https://github.com/axel-op/googlejavaformat-action/commit/b57c61e920143b8f12cd492d9a9a31f2a2d2f803) in work to move to Node16, but a new tag and release version has not been created to include the change.  Could you please cut a new version with the update? Thanks?

**Comment by axel-op** [comment]
Hello @GeofferyMedved,

The commit setting the Node version to 16 has been pushed in the [v3](https://github.com/axel-op/googlejavaformat-action/commits/v3) branch. You can reference this branch in your workflow like this:

```yml
jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
```

Does that solve your problem?

**Comment by GeofferyMedved** [comment]
My fear is that the `v3` branch could be deleted and then underlying builds could be effected.  Would you be able to tag this branch so that ref can be referenced instead? Otherwise I'd be happy to fork the project if that is easier for you.

**Comment by axel-op** [comment]
You want to harden the security of your workflow by freezing the reference of this action.

Unfortunately, [tags can be moved or deleted](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) as much as branches.

If you really want to make sure that the reference is "immutable", the recommended way to that is to use the SHA of a commit instead, as shown in this example:

```yml
jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@dbff853fb823671ec5781365233bf86543b13215
        with:
          args: "--skip-sorting-imports --replace"
```

By doing this, your workflow will always use the same version of the action.
