### ISSUE TITLE
Version 3.3.0 is breaking the action.

### ISSUE THREAD

**Issue by TomerFi** [axel-op/googlejavaformat-action#6]
Version [3.3.0](https://github.com/axel-op/googlejavaformat-action/releases/tag/v3.3.0) breaks the action.

My configuration was:
```yaml
      - name: Check java style format
        uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
```

Which worked well until the recent 3.3.0 release.
Now it fails and throws:
```text
Error: Parameter token or opts.auth is required
```

Pinning version [3.2.0](https://github.com/axel-op/googlejavaformat-action/releases/tag/v3.2.0), fixed the issue for me:

```yaml
      - name: Check java style format
        uses: axel-op/googlejavaformat-action@v3.2.0
        with:
          skipCommit: true
```
